  version: "3.8"
  
  services:
    application:
      build:
        context: .
        dockerfile: ./application/Dockerfile
      ports:
        - 8000

    envoy:
      build:
        context: .
        dockerfile: ./envoy/Dockerfile
      ports:
        - "10000:10000"
      depends_on:
        - application